language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node

stages:
  - compile
  - deploy
  - release

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

jobs:
  include:
    - if: branch = master
    - stage: compile
      script: "yarn build"
    - stage: deploy
      script: "yarn deploy"
    - stage: release
      script: "yarn semantic-release"